### ISSUE TITLE
Accept weeks and months parameter in harness.flush();

### ISSUE THREAD

**Issue by yrimal** [medic/cht-conf-test-harness#124]
Curret harness.flush accepts years,days,hours,minutes,seconds,ms which is great.
I think adding `months` and `weeks` would be useful as in cht-core and in app, we mostly talk about schedules in terms of weeks and months. 

Ability to call `await flush({ weeks: 4});` would be really helpful.

**Comment by kennsippell** [comment]
@eljhkrr Can you confirm this will be fixed by https://github.com/medic/cht-conf-test-harness/pull/118?

**Comment by eljhkrr** [comment]
Yes, it's included
