### ISSUE TITLE
harness.setNow() doesn't accept luxon DateTime object.

### ISSUE THREAD

**Issue by yrimal** [medic/cht-conf-test-harness#134]
harness.setNow() doesn't accept luxon Datetime object directly. Current workaround for this is to pass toString() so that setNow() considers input as string and works accordingly. 

Since we are using luxon more, we need to make harness.setNow() and if any other date/time function support luxon date/time.

**Comment by kennsippell** [comment]
harness.flush() might take a luxon `Duration` object?

**Comment by yrimal** [comment]
This appears to be fixed in latest release with this [PR](https://github.com/medic/cht-conf-test-harness/pull/118).
