### ISSUE TITLE
Include support for CHT-Core latest releases

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-conf-test-harness#138]
**Description**
Include support for CHT-Core latest releases.

**Additional context**
We've created a new config inside of CHT-Core and have a couple of tests that we'd like to include but these need 3.13 features to run. So creating this ticket to track after CHT-Core 3.13 release.

**Comment by kennsippell** [comment]
> we can't merge these tests yet since the forms are using a new XPath function that parses timestamps to date object

Quote from https://github.com/medic/cht-core/pull/7299. Can I ask @latin-panda what are the new XPath functions added? I'm checking the 3.13 release notes and not seeing a mention.

**Comment by latin-panda** [comment]
Hi @kennsippell, sorry about that, it should have include more details.

This is the new XPath function: [parse-timestamp-to-date](https://docs.communityhealthtoolkit.org/apps/reference/forms/app/#parse-timestamp-to-date)

There's also a new Enketo widget: [android-app-launcher](https://docs.communityhealthtoolkit.org/apps/reference/forms/app/#android-app-launcher)

This is [the PR ](https://github.com/medic/cht-core/pull/7248) that introduced these features.
