### ISSUE TITLE
Add a way to set values to fields regardless of its attributes

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-conf-test-harness#139]
**Is your feature request related to a problem? Please describe.**
It'd be helpful to have a way to set values to fields regardless of its attributes (hidden, required, readonly, ...)

For example a field is required but has appearance hidden, then when running test case, it can't set the value ([current validation code](https://github.com/medic/cht-conf-test-harness/blob/6dbef598c35c53cf0bd0757f068539288c1943ab/src/form-host/form-filler.js#L248)) and an error occurs when filling the form: “Required fields missing” 

```
--- form inputs file ----
module.exports = {
  my_form: [['a09b9570-116e-11ec-82a8-0242ac130003'], [], [-12.113344], ['RUNNING']],

--- test case ----

it('Should show correct task when form is submitted', async () => {
    const result = await harness.fillForm('my_form', ...formInputs.my_form);
```

**Describe alternatives you've considered**
It'd be nice to use field name + group(s) name to find a field regardless if it’s visible, required, optional, readonly, hidden, or location deepness (groups). So we can pass something like key:value
```
"/inputs/contact/parent/name": "Facility abc"
-------- then
$([name="field_key"]).value(field_value) 
```
- It doesn't rely in array position, if same level groups change order, the test won't be affected. No need to add empty arrays representing pages.
- Easier to spot errors while building the form inputs for tests, because field location is specified. So no unexpected fields getting wrong values. 
- Have to check or be careful about performance if doing this approach. 
- Have to be backward compatible to not break existing tests.

**Additional context**
We were designing a form where some fields are automatically populated after a button action, these fields have hidden appearance because the data wasn't friendly or not relevant to the user, additionally the fields are required to prevent the user of continuing to the next page without performing the action. 

Samples:
| type | name | label | appearance | required | default | ... |
|---|---|---|---|---|---|---|
| string | case_uuid | NO_LABEL | hidden |  yes |  | ... |
| string | latitude | NO_LABEL | hidden |  yes |  | ... |

At the end to move forward, we've worked around the form design because test coverage is important however the UX decreased.

**Comment by kennsippell** [comment]
Currently, the behaviour of `fillForm` simply emulates the behaviour of users.  Completing operations like "set a value for a hidden field" is a paradigm shift - which is fine.  I suspect what might be preferred is to support cht-core enketo widgets as first-class citizens in the harness. https://github.com/medic/cht-conf-test-harness/issues/46

For now - as a workaround, consider this workaround:

`harness.page.evaluate(() => $$('input[name$="/breath_timer"]').removeAttr('data-required')`

https://github.com/medic/config-muso/blob/master/test/widget-hacks.js

**Comment by kennsippell** [comment]
Please reactivate if the above workaround is not satisfactory.

**Comment by kennsippell** [comment]
Please reactivate if the above workaround is not satisfactory.
