### ISSUE TITLE
Recalculation for targets depending on time only

### ISSUE THREAD

**Issue by IreneAchola** [medic/cht-conf-test-harness#145]
There are [some targets](https://docs.google.com/spreadsheets/d/1EnDv7oUzAYHtMCkMem8vzf-Z1jolyliBL0A1MtMJYCU/edit#gid=2002400666&range=C7) that give an update of what appointments are within a given period of time. This has worked in the past, but now, target recalculation is done every 7 days or when contact data changes as [shown in this test](https://github.com/medic/config-vhw/blob/master/test/targets/immunization-visits.spec.js#L89-L112).

It is possible that data might actually not be submitted in real life to force that recalculation, and it will have to be done after 7 days (https://github.com/medic/config-vhw/pull/127#discussion_r722661702). I believe this issue may stem from other issues, e.g.;

- Do users/partners actually need this target, is it something they use frequently, is it useful to them?
- Do they interpret it correctly given that most of the other targets give information on work that has happened vs upcoming work
- What is the goal of this target?
- Is there a more visible way that this can be implemented if the users need it?

In as much as we may purpose to fix it here, it might be that we are not addressing the actual issue.
https://github.com/medic/config-vhw/pull/127#discussion_r722667811

cc @derickl

**Comment by kennsippell** [comment]
These targets are going to be broken in production. If these targets are useful, I believe this needs to be a cht-core issue not a cht-conf-harness issue. The harness here is behaving just like the core - which is desired. The problem appears to be the v3.8 unceremoniously dropped support for targets like this "xyz due in the next 7 days".

**Comment by derickl** [comment]
@IreneAchola following up on whether you feel this is useful to move to cht-core as per the previous comment.

**Comment by IreneAchola** [comment]
Given that VHW had to review their in app targets, this is a [blocked issue.](https://github.com/medic/config-vhw/issues/141)
