### ISSUE TITLE
harness.setNow() doesn't support Luxon date from newer version.

### ISSUE THREAD

**Issue by yrimal** [medic/cht-conf-test-harness#146]
**Describe the bug**
harness.setNow() fails when we pass date created from latest version (2.1.1)

**To Reproduce**
1. Update luxon to 2.1.1 or later.
2. Create the date using luxon for e.g:
```js
const today = DateTime.fromISO('2010-01-01', { zone: 'utc' });
```
3. Pass this date to Harness.
```js
harness.setNow(today);
```

**What happened?**
Error is thrown:
```
Error: Unsupported date value
    at toDate (node_modules/cht-conf-test-harness/src/dateUtils.js:26:9)
    at Harness.setNow (node_modules/cht-conf-test-harness/src/harness.js:248:25)
    at Context.<anonymous> (test/app/family_planning.spec.js:11:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**What did you expect?**
Set date successfully. 

**Screenshots**

**Environment:**
 - Version: 2.2.4

**Comment by eljhkrr** [comment]
Insights from duplicate issue:

> setNow() supports passing in a DateTime object which is confirmed to be so with an instanceof check. This has been discovered to not work across different major Luxon versions - 1.x and 2.x. Luxon has a isDateTime method that 'works across context boundaries'.
> Similarly, flush() supports Luxon durations cross-checked using instanceof. There's also an isDuration method.
