### ISSUE TITLE
Add support for cht-core 3.12 and 3.13

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#148]
**3.12**
- [x] Standard stuff for 3.12
- [x] Add support for the [cht-api](https://docs.communityhealthtoolkit.org/apps/reference/tasks/#cht-api) in 3.12

**3.13**
- [x] Standard stuff for 3.13
- [ ] ~Support for new [XPath functions](https://github.com/medic/cht-core/pull/7299) including [to-bikram-sambat](https://github.com/medic/cht-core/blob/master/webapp/src/js/enketo/medic-xpath-extensions.js#L97)~
- [x] parse-timestamp-to-date

**Comment by kennsippell** [comment]
@latin-panda Did you do a prototype for supporting the cht-api in 3.12?

**Comment by latin-panda** [comment]
Hi @kennsippell! I just found my branch that I used to mock the cht-api back then: https://github.com/medic/cht-conf-test-harness/tree/adding-cht-script-api-mock
It probably needs more work...

**Comment by kennsippell** [comment]
Looks like to-bikram-sambat isn't in 3.13, but `parse-timestamp-to-date` is.

**Comment by kennsippell** [comment]
Released as v2.3.0
