### ISSUE TITLE
harness.flush() does not consider DST changes when moving forward in days

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-conf-test-harness#20]
`harness.flush()` does not consider DST changes when moving forward in days. This is causing the CHT-Reference-App tests to fail for certain timezones.

For example, in Canada/Pacific timezone on `Sunday 3 November 2019  02:00 local time`, DST ends.
```
harness.setNow('2019-11-03');
//1572764400000 (Canada/Pacific: 2019-11-03 00:00:00 / GMT: 2019-11-03 07:00:00)
harness.flush(1);//Move forward by 1 day
harness.getNow();
```
Expected: `1572854400000` (Canada/Pacific: 2019-11-04 **00:00:00** / GMT: 2019-11-04 08:00:00)
Actual: `1572850800000` (Canada/Pacific: 2019-11-03 **23:00:00** / GMT: 2019-11-04 07:00:00)

However,`harness.setNow()` works fine.

Attached is a test spec to demonstrate the problem. When running with `TZ=Canada/Pacific`, the test fails. But with `TZ=Pacific/Pitcairn` (no DST change), it passes.
[harness-tz.spec.js.zip](https://github.com/medic/medic-conf-test-harness/files/4049140/harness-tz.spec.js.zip)

**Comment by kennsippell** [comment]
Let's replace `flush` and `toDate` with luxon.
