### ISSUE TITLE
getTasks({ title: 'val' }) doesn't filter properly for tasks using translation key arrays

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#212]
**To Reproduce**
1. Create a task [like this one](https://docs.communityhealthtoolkit.org/apps/reference/tasks/#tasksjs-2) using an array of translation keys
2. Using harness to trigger the task with `getTasks({ title: 'Postnatal visit needed' })`

**What did you expect?**
The task was triggered and should be returned

**What happened?**
Nothing is returned because the task filter doesn't work with translation arrays

**Comment by garethbowen** [comment]
PR to update the example in the documentation: https://github.com/medic/cht-docs/pull/1027

**Comment by freddieptf** [comment]
Closed as the recommended way is using a translation key, linked example in the docs has been updated
