### ISSUE TITLE
Add timeout to build jobs

### ISSUE THREAD

**Issue by derickl** [medic/cht-conf-test-harness#218]
This [run](https://github.com/medic/cht-conf-test-harness/actions/runs/4576335333/jobs/8080332247?pr=217) took 6 hours before timing out. That's a huge waste of build minutes

The solution would be adding a timeout similar to  https://github.com/medic/config-ug-vht/blob/master/.github/workflows/build.yml#L14

**Comment by KicaRonaldOkello** [comment]
This was fixed in #217
