### ISSUE TITLE
support testing datetime input type

### ISSUE THREAD

**Issue by benkags** [medic/cht-conf-test-harness#234]
**Describe the bug**
The value provided for `datetime` input type gets populated in both the rendered date and time fields as is. As a result validation always fails because the rendered date type expects a date value and the rendered time type expects a time value. 

**To Reproduce**
1. Create an app form with a `datetime` input type.
2. Add a unit test for the form providing valid a `datetime` value.
3. Run the unit test.
4. Observe as the test fails with a validation error.

**What happened?**
Unit test for a `datetime` type fails with a validation error because the provided datetime value is populated in both the rendered date and time fields as is. 

**What did you expect?**
Unit test accepts provided `datetime` value as valid.

**Screenshots**

**Environment:**
 - Device: Desktop
 - Browser: chrome
 - Version: "cht-conf-test-harness": "^2.4.3"
 - Android version: []
 - Phone make: 

**Additional context**
_You can indicate which users experienced the problem (only name and location without password)_

**Comment by kennsippell** [comment]
Hey @benkags! Pleased to have you back :)  

Do you happen to have a pull request with an example failing test? I attempted a quick repro in [this branch 234-datetime-field](https://github.com/medic/cht-conf-test-harness/tree/234-datetime-field). Maybe it is just easier to work together on your scenario.  Is the failing test in https://github.com/moh-kenya/config-echis-2.0/pull/973 ?

**Comment by benkags** [comment]
Hey @kennsippell. Thank you!

Looks like the question has be marked as required to trigger the validation.
