### ISSUE TITLE
Harness error saving contact form

### ISSUE THREAD

**Issue by jonathanbataire** [medic/cht-conf-test-harness#239]
## Description
When filling this [clinic-create form](https://github.com/medic/config-ug-vht/blob/master/forms/contact/clinic-create.xlsx) harness throws the error below.
failing input: 
```
[["no","Joe","","male",40,"","","2000-01-01","national","CN123456789076","no","no","negative","no","no","no","no","no","yes","yes"],
["no"], 
["yes","yes","yes","yes","yes","yes","yes","yes","yes","yes","yes","yes"]]
```

I find that the begin group with name "repeat" is causing this. renaming it solves this harness issue but the repeat group wont be able to generate other hh members
The form works fine in cht-core 4.2.2
### environment
Harness Version: 3.0.10

```
Error encountered while filling form: [
  {
    "type": "save",
    "msg": "Failed to save app form: TypeError: Cannot read properties of undefined (reading 'map')"
  }
]
```

**Comment by kennsippell** [comment]
Releasing as 3.0.12
