### ISSUE TITLE
getContactSummary only loads reports at current level in hierachy. Reports from below are not loaded

### ISSUE THREAD

**Issue by billwambua** [medic/cht-conf-test-harness#240]
**Describe the bug**
CHT Conf Test Harness only pulls reports at one level in the hierachy when simulating contact summary activity instead of pulling reports from that level to the lowest level in the hierachy.

**To Reproduce**
1. Make sure you have a proper hierachy setup in your project harness.defaults.json. [Example](https://github.com/moh-kenya/config-echis-2.0/blob/main/harness.defaults.json)
2. Fill a report `report-1` for a Household member
3. Switch subject to Household. [Example](https://github.com/moh-kenya/config-echis-2.0/blob/69bcc124e3cd402e6c535bc842d30a85d3763c2f/test/forms/mute_person.spec.js#L128)
4. You will notice that the `report-1` will not be visible at the household

**What happened?**
In Contact Summary, if `reports` is passed to a function, CHT pulls reports at that level in the hierachy downwards. e.g if you pull reports at the household level, it will pull reports reported at the household as well as household member reports.

In contrast for the exact same scenario, CHT Conf Test Harness pulls reports at the household level only.

This makes tests inaccurate in predicting instance behaviour.

**What did you expect?**
The report to show up when the subject is above the level of submission.

**Screenshots**
In the instance, I am able to see the reports submitted from levels below. E.g Household member reports at the household level.

![Selection_170](https://github.com/medic/cht-conf-test-harness/assets/17000106/553ea844-0b54-4323-bffd-bae68fe10712)

But using CHT Conf Test Harness, I am not able.

![Selection_171](https://github.com/medic/cht-conf-test-harness/assets/17000106/efd8beb9-55aa-4dfd-ab26-bf3782370fc3)

**Environment:**
 - Ubuntu 20.04
 - CHT Version `3.18.3`

**Additional Context**
Find a PR affected by this [here](https://github.com/moh-kenya/config-echis-2.0/pull/1295#issuecomment-1694616500).

**Comment by kennsippell** [comment]
@billwambua Can you help me to understand this issue more clearly? 

What exactly are you logging in CHT for the screenshot with the red boxes? CHT passes a [few globals into contact summary](https://github.com/medic/cht-core/blob/282cafc1e97241a6128c92e6f3c1e3cd54212a7a/webapp/src/ts/services/contact-summary.service.ts#L41): contact, reports, lineage, uhcStats, cht, targetDoc.  Are you saying the reports of all the contact's descendents are present in one of these objects?

What are you logging in the test? I ran `npx mocha test/forms/mute_person.spec.js --timeout 50000`, but I don't see any log output. The branch from https://github.com/moh-kenya/config-echis-2.0/pull/1295 has been deleted. Looking through your commits I can't find the log statements.

**Comment by kennsippell** [comment]
From CHT 4.4:

Reports passed to contact summary are the result of https://github.com/medic/cht-core/blob/master/webapp/src/ts/effects/contacts.effects.ts#L130C22-L130C22

Builds a list of IDs for all of the selected contact's children https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/contact-view-model-generator.service.ts#L327

Converts to subjectId and then does a "report search" https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/contact-view-model-generator.service.ts#L307

Calls search passes the subjectIds to `medic-client/reports_by_subject`

cht-core isn't actually fetching all reports of all descendants, it actually fetches all reports for the selected contact + all immediate children.

This is not what is documented for data being passed into the contact-summary. https://docs.communityhealthtoolkit.org/apps/reference/contact-page/

>  reports -  An array of reports for the contact.

**Comment by kennsippell** [comment]
Behavior is the same on `3.10.5`
