### ISSUE TITLE
Support for CHT Core 4.11

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#263]
**Is your feature request related to a problem? Please describe.**
Support for CHT core 4.8

**Describe the solution you'd like**
Support it

**Describe alternatives you've considered**
Take a nap

**Comment by aloundoye** [comment]
Hi @kennsippell, will this version support the [functions](https://docs.communityhealthtoolkit.org/building/reference/forms/app/#chtdifference-in-years) introduced in version 4.7?

**Comment by kennsippell** [comment]
@aloundoye Yes it should! You can try out branch https://github.com/medic/cht-conf-test-harness/pull/264 if you'd like to experiment. I believe it is in a usable state but not ready to commit.
