### ISSUE TITLE
Load the cht-core enketo widgets

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#46]
Currently the cht-core enketo widgets aren't loaded into the test harness. Can we load them to make the forms in the harness more closely behave like the forms in the webapp?

**Comment by kennsippell** [comment]
This is pretty challenging:

1. There is some weird syntax around some of the widgets that prevent them from building into our library. We can work around this with module rule `{ test: /\/enketo\/widgets/i, use: 'script-loader' }` or alike.
1. Several of the widgets directly call angular services (Android-datepicker, bikram-sambat-datepicker, db-object-widget, mrdt, notewidget, phone-widget, simprints)

Is this depth of integration possible? Is this wise? What are the limits of the harness and when is the right time to just build an e2e test?

**Comment by kennsippell** [comment]
This depth of integration is likely beyond the abilities of this framework :(

**Comment by kennsippell** [comment]
Hope!

**Comment by jkuester** [comment]
@kennsippell do you think we can consider this issue to be addressed now?  AFIK, pretty much all the widgets should load fine in the harness except for the db-object widget (which is being tracked in https://github.com/medic/cht-conf-test-harness/issues/184).

**Comment by kennsippell** [comment]
Yep!!!
