### ISSUE TITLE
Inconsistent behaviour of enketo relevant field in cht-production vs harness

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#78]
Update family_planning_men form for production muso configuration.

For field: `visited_contact_uuid` set `relevant` to `${s_reg_how_found} = 'during_home_visit'` and `calculation` to `../inputs/contact/parent/_id`.

Run this configuration and test scenario:

1. Fill in family_planning_men form specifying the visit was a 'house visit'
2. fields.visited_contact_uuid is set properly

Execute the following test:

```
  it('home visit', async () => {
    const inputs = familyPlanningForMenScenarios.noCouncil();
    const result = await harness.fillForm(Forms.FAMILY_PLANNING_FOR_MEN, ...inputs);
    expect(result.report.fields.visited_contact_uuid).to.eq(contactId);
  });
```

Test fails because `result.report.fields.visited_contact_uuid` is empty.
Workaround is to set `calculation` value to `if(${s_reg_how_found} = 'during_home_visit', ../inputs/contact/parent/_id,’’)` which works for both test harness and e2e testing.
https://github.com/medic/config-muso/pull/160#discussion_r548356070

Investigate and correct whatever is causing the difference?

**Comment by derickl** [comment]
Related to https://github.com/medic/cht-conf-test-harness/issues/133

**Comment by kennsippell** [comment]
Closing as duplicate of #133.
